typedef wchar_t *LPWSTR;

[
   uuid(C4E7D548-8986-428f-8B12-5FD293A1A741),
   version(1.0)
]

interface exosvc
{
   const unsigned long MAX_BUF_SIZE = 1024;
   const unsigned long HASH_256_SIZE = 32;

   void GetExoSvcVersion(
      [in] handle_t hBinding,
      [out] unsigned long *Version
   );

   int Shutdown(
      [in] handle_t hBinding
   );

   long AddInteger(
      [in] handle_t hBinding,
      [in] long param1,
      [in] long param2
   );

   int Hash256InWorkerProcess(
      [in]handle_t hBinding,
      [in, range(0, MAX_BUF_SIZE)] unsigned long ulBufferSize,
      [in, size_is(ulBufferSize)] byte pbBufferToHash[],
      [out, size_is(HASH_256_SIZE)] byte pbResult[]
   );

   int GetProcessTokenDescription(
      [in] handle_t hBinding,
      [out, string] LPWSTR *szTokenDescription
   );

   int ImpersonateAndGetThreadTokenDescription(
      [in] handle_t hBinding,
      [out, string] LPWSTR *szTokenDescription
   );
}
